# Generated by Django 4.1.3 on 2022-11-14 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posbon_name', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=255, verbose_name='Shahar/Tuman')),
                ('quarter', models.CharField(max_length=255, verbose_name='MFY nomi')),
                ('person_name', models.CharField(max_length=255, verbose_name='Ism/Familiya')),
                ('male', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default=None, max_length=10, verbose_name='Jinsi')),
                ('birthdate', models.DateField(verbose_name="Tug'ilgan sana")),
                ('passport_serie_or_id', models.CharField(max_length=15, verbose_name='Passport seriya yoki ID')),
                ('address', models.CharField(max_length=300, verbose_name='Yashash manzili')),
                ('registration_address', models.CharField(max_length=300, verbose_name='Doimiy yashash manzili')),
                ('deputat', models.CharField(choices=[('resp', 'Respublika'), ('vil', 'Viloyat'), ('city', 'Shahar/Tuman')], default="Yo'q", max_length=5, verbose_name='Xalq deputatlari kengashi')),
                ('family_status', models.CharField(choices=[('married', 'Oilali'), ('nomarried', 'Oilasiz'), ('divorce', 'Ajrashgan'), ('illegal', 'Noqonuniy nikoh')], max_length=10, verbose_name='Oilaviy ahvoli')),
                ('invalid_group', models.CharField(max_length=30, verbose_name='Nogironligi')),
                ('job', models.CharField(default='Ishsiz', max_length=300, verbose_name='Mehnatga layoqatligi')),
                ('social_status', models.CharField(choices=[('tdaftar', 'Temir daftari'), ('adaftar', 'Ayollar daftari'), ('ydaftar', 'Yoshlar dartari')], default="Yo'q", max_length=10, verbose_name='Ijtimoiy ahvoli')),
                ('housing', models.CharField(choices=[('ijara', 'Ijarada'), ('ijarasiz', 'Noturar binoda')], default="Yo'q", max_length=20, verbose_name='Uy-joy muhtojligi')),
                ('education', models.CharField(choices=[('orta', "O'rta"), ('orta-maxsus', "O'rta maxsus"), ('oliy', 'Oliy')], default="o'rta", max_length=20, verbose_name="Ma'lumoti")),
                ('cow', models.PositiveIntegerField(null=True, verbose_name='Qoramol, Chorva soni')),
                ('poultry', models.PositiveIntegerField(null=True, verbose_name='Parrandalar soni')),
                ('pet', models.PositiveIntegerField(null=True, verbose_name='It, mushuklar soni')),
                ('convicted', models.CharField(choices=[('sud', 'Sudlangan'), ('sudlanmagan', 'Sudlanmagan')], max_length=15, verbose_name='Sudlanganligi')),
                ('long_time', models.CharField(default="Yo'q", max_length=10, verbose_name='Uzoq vaqtga ketgan')),
                ('came_long_time', models.CharField(default="Yo'q", max_length=10, verbose_name='Uzoq muddatdan qaytib kelgan')),
                ('crime', models.CharField(default="Yo'q", max_length=10, verbose_name='Jinoyat sodir etganmi')),
                ('troubled', models.CharField(default="Yo'q", max_length=10, verbose_name='Notinch oila vakili')),
                ('psychotropic', models.CharField(default="Yo'q", max_length=5, verbose_name="Psixotrop, narkotik modda iste'mol qiladi")),
                ('mentally_ill', models.CharField(default="Yo'q", max_length=5, verbose_name='Ruxiy kasal')),
                ('alcoholic_person', models.CharField(default="Yo'q", max_length=5, verbose_name="Spirtli ichimlikka ro'jo qo'ygan")),
                ('whore_woman', models.CharField(default="Yo'q", max_length=5, verbose_name='Yengil tabiat ayol')),
                ('posbon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
