# Generated by Django 4.1.3 on 2022-11-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='cow',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Qoramol, Chorva soni'),
        ),
        migrations.AlterField(
            model_name='population',
            name='education',
            field=models.CharField(choices=[('orta', "O'rta"), ('orta-maxsus', "O'rta maxsus"), ('oliy', 'Oliy')], default="O'rta", max_length=20, verbose_name="Ma'lumoti"),
        ),
        migrations.AlterField(
            model_name='population',
            name='family_status',
            field=models.CharField(choices=[('married', 'Oilali'), ('nomarried', 'Oilasiz'), ('divorce', 'Ajrashgan'), ('illegal', 'Noqonuniy nikoh')], max_length=10, null=True, verbose_name='Oilaviy ahvoli'),
        ),
        migrations.AlterField(
            model_name='population',
            name='housing',
            field=models.CharField(choices=[('ijara', 'Ijarada'), ('ijarasiz', 'Noturar binoda')], max_length=20, null=True, verbose_name='Uy-joy muhtojligi'),
        ),
        migrations.AlterField(
            model_name='population',
            name='pet',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='It, mushuklar soni'),
        ),
        migrations.AlterField(
            model_name='population',
            name='poultry',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Parrandalar soni'),
        ),
        migrations.AlterField(
            model_name='population',
            name='social_status',
            field=models.CharField(choices=[('tdaftar', 'Temir daftari'), ('adaftar', 'Ayollar daftari'), ('ydaftar', 'Yoshlar dartari')], max_length=10, null=True, verbose_name='Ijtimoiy ahvoli'),
        ),
    ]
